name: aEventos
version: ${project.version}
description: O seu plugin de eventos!

authors:
    - Ars3ne
    - LMS5413
website: ${project.url}

main: com.ars3ne.eventos.aEventos
softdepend: [LegendChat, SimpleClans, Vault, PlaceholderAPI]
api-version: 1.13

commands:
  evento:
    description: Comando principal do plugin.