name: Publish package to GitHub Packages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build
        run: mvn clean install
      - name: Get version from pom.xml
        id: get_version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
          token: ${{ secrets.JAVA_TOKEN }}
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ${{ github.event.head_commit.message }}